module.exports = {
  purge: [
    "./components/**/*.js",
    "./pages/**/*.js",
    "./layouts/**/*.js",
    "./slices/**/*.js",
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        valetBlack: "#1B2326",
        valetBlackBlack: "#13121b",
        valetGold: "#574B38",
        valetYellow: "#C79A3D",
        valetBlue: "#12141E",
        valetLight: "#F6F2E6",
        valetUltraLight: "#F9F7F2",
        valetPink: "#ed6b6d",
        valetPurple: "#8f81b9",
        valetDeepNight: "#070B1A",
      },
      screens: {
        xs: "375px",
        xssm: "480px",
        sm: "640px",
        md: "768px",
        mdlg: "960px",
        lg: "1024px",
        lgxl: "1140px",
        xl: "1280px",
        "2xl": "1440px",
        "3xl": "1680px",
        "4xl": "1920px",
        "5xl": "2200px",
        "6xl": "2400px",
        "7xl": "2600px",
        "8xl": "2800px",
        "9xl": "3000px",
      },
      fontSize: {
        sm: ["0.9rem", { lineHeight: "1.25rem" }],
        smmd: ["1rem", { lineHeight: "1.25rem" }],
        md: ["1.25rem", { lineHeight: "1.75rem" }],
        lg: ["1.5rem", { lineHeight: "2rem" }],
        xl: ["2.0rem", { lineHeight: "2.5rem" }],
        "2xl": ["3.0rem", { lineHeight: "3.0rem" }],
        "3xl": ["3.4rem", { lineHeight: "3.2rem" }],
        "4xl": ["3.7rem", { lineHeight: "3.4rem" }],
        "5xl": ["4.8rem", { lineHeight: "4.2rem" }],
        "6xl": ["5.8rem", { lineHeight: "5.2rem" }],
        "7xl": ["6.8rem", { lineHeight: "6.2rem" }],
        "8xl": ["7.8rem", { lineHeight: "7.2rem" }],
        "9xl": ["8.8rem", { lineHeight: "8.2rem" }],
        "10xl": ["10.0rem", { lineHeight: "9.4rem" }],
      },
      maxWidth: {
        "7xl": "80rem",
        "8xl": "88rem",
        "9xl": "90rem",
      },
      aspectRatio: {
        "2.35/1": "2.35 / 1",
      },
    },
    fill: (theme) => ({
      white: theme("colors.white"),
      black: theme("colors.black.500"),
    }),
    aspectRatio: {
      1: "1",
      2: "2",
      3: "3",
      4: "4",
    },
  },
  variants: {
    extend: {
      fill: ["hover", "focus"],
    },
    aspectRatio: ["responsive", "hover"],
  },
  plugins: [require("@tailwindcss/aspect-ratio")],
};
