// This file is generated by Slice Machine. Update with care!

import BannerSlice from './BannerSlice';
import CareersForm from './CareersForm';
import Catalog from './Catalog';
import ContactForm from './ContactForm';
import FeaturedImage from './FeaturedImage';
import FullWidthImage from './FullWidthImage';
import Hero from './Hero';
import HeroTertiary from './HeroTertiary';
import ImageGallery from './ImageGallery';
import Instagram from './Instagram';
import Locations from './Locations';
import Map from './Map';
import OptOutForm from './OptOutForm';
import Quote from './Quote';
import QuoteSlice from './QuoteSlice';
import TextSlice from './TextSlice';
import Video from './Video';

export {
	BannerSlice,
	CareersForm,
	Catalog,
	ContactForm,
	FeaturedImage,
	FullWidthImage,
	Hero,
	HeroTertiary,
	ImageGallery,
	Instagram,
	Locations,
	Map,
	OptOutForm,
	Quote,
	QuoteSlice,
	TextSlice,
	Video,
};

export const components = {
	banner_slice: BannerSlice,
	careers_form: CareersForm,
	catalog: Catalog,
	contact_form: ContactForm,
	featured_image: FeaturedImage,
	full_width_image: FullWidthImage,
	hero: Hero,
	hero_tertiary: HeroTertiary,
	image_gallery: ImageGallery,
	instagram: Instagram,
	locations: Locations,
	map: Map,
	opt_out_form: OptOutForm,
	quote: Quote,
	quote_slice: QuoteSlice,
	text_slice: TextSlice,
	video: Video,
};
